name: emberfall
description: Emberfall - An epic 2D adventure
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.23.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/player/Main Characters/Virtual Guy/
    - assets/images/player/Main Characters/Mask Dude/
    - assets/images/player/Main Characters/Ninja Frog/
    - assets/images/player/Main Characters/Pink Man/
    - assets/images/enemies/
    - assets/images/items/Fruits/
    - assets/images/items/Boxes/Box1/
    - assets/images/items/Checkpoints/Start/
    - assets/images/items/Checkpoints/End/
    - assets/images/items/Checkpoints/Checkpoint/
    - assets/images/terrain/Terrain/
    - assets/images/background/Background/
    - assets/images/effects/Other/
    - assets/images/traps/Traps/
    - assets/images/traps/Spikes/
    - assets/images/traps/Saw/
    - assets/images/traps/Fire/
    - assets/images/traps/Fan/
    - assets/images/traps/Falling Platforms/
    - assets/images/traps/Trampoline/
    - assets/images/traps/Platforms/
    - assets/images/ui/Menu/Buttons/
